# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3

    # cache the dependencies from any node_modules directory
#    - name: cache dependencies
#      uses: actions/cache@v2
#      with:
#        path: '**/node_modules'
#        key: node_modules-${{ hashFiles('**/package-lock.json')}}

    - run: npm install

    - name: Cache Chrome
      id: chrome-cache
      uses: actions/cache@v3
      with:
        path: /opt/hostedtoolcache/chromium/
        key: ${{ runner.os }}-chrome
        restore-keys: |
          ${{ runner.os }}-chrome

    #    - run: ls -al /opt/hostedtoolcache/
    #    - run: ls -al /opt/hostedtoolcache/chromium/

    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1
  #      if: steps.chrome-cache.outputs.cache-hit != 'true'

    - run: npm run build --if-present
    - run: npm test
      env:
        CARBONATE_USER_ID: ${{ secrets.CARBONATE_USER_ID }}
        CARBONATE_API_KEY: ${{ secrets.CARBONATE_API_KEY }}
